CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   VARCHAR(50) UNIQUE NOT NULL,
    name    VARCHAR(50)        NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    created     TIMESTAMP    NOT NULL,
    user_id     INTEGER      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    available   BOOLEAN      NOT NULL,
    owner_id    INTEGER      NOT NULL,
    request_id  INTEGER,
    foreign key (owner_id) references users (user_id) ON DELETE CASCADE,
    foreign key (request_id) REFERENCES requests (request_id)
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP   NOT NULL,
    end_time   TIMESTAMP   NOT NULL,
    item_id    INTEGER     NOT NULL,
    booker_id  INTEGER     NOT NULL,
    STATUS     VARCHAR(10) NOT NULL,
    foreign key (booker_id) references users (user_id) ON DELETE CASCADE,
    foreign key (item_id) references items ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(255) NOT NULL,
    item_id    INTEGER      NOT NULL,
    author_id  INTEGER      NOT NULL,
    created    TIMESTAMP    NOT NULL,
    foreign key (item_id) references items ON DELETE CASCADE,
    foreign key (author_id) references users (user_id) ON DELETE CASCADE
);